
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


// import { useEffect, useState } from "react";
// import { motion } from "framer-motion";
// import { usePathname } from "next/navigation";
// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };
// export default function Layout({ children }: { children: React.ReactNode }) {
//   const pathname = usePathname(); // Ensure animation triggers on navigation
//   const [animationKey, setAnimationKey] = useState(0);


//   const geistSans = Geist({
//       variable: "--font-geist-sans",
//       subsets: ["latin"],
//     });
    
//     const geistMono = Geist_Mono({
//       variable: "--font-geist-mono",
//       subsets: ["latin"],
//     });
    
 
//   useEffect(() => {
//     setAnimationKey((prev) => prev + 1);
//   }, [pathname]);

//   const svgVariants = {
//     hidden: { rotate: -180 },
//     visible: {
//       rotate: 0,
//       transition: { duration: 1, delay: 5 },
//     },
//     zoomed: {
//       scale: 20,
//       transition: {
//         duration: 2,
//         delay: 8,
//         ease: "easeInOut",
//       },
//     },
//     movedRight: {
//       x: 200,
//       transition: {
//         type: "spring",
//         stiffness: 100,
//         damping: 10,
//       },
//     },
//   };

//   const pathVariants = {
//     hidden: { opacity: 0, pathLength: 0 },
//     visible: {
//       opacity: 1,
//       fill: ["gray", "black", "gray"],
//       pathLength: 1,
//       transition: {
//         duration: 5,
//         delay: 2,
//         ease: "easeInOut",
//         fill: { duration: 2, repeat: Infinity, repeatType: "reverse" },
//       },
//     },
//     fullWhite: {
//       fill: "white",
//       transition: { duration: 10, delay: 7 },
//     },
//   };

//   const lineVariant1 = {
//     hidden: { width: 0, opacity: 1, x: -180 },
//     expand: {
//       x: 0,
//       width: 50,
//       transition: { duration: 2, ease: "easeOut" },
//     },
//     fadeOut: {
//       opacity: 0,
//       transition: { duration: 1, delay: 3 },
//     },
//   };
//   const lineVariant2 = {
//     hidden: { width: 0, opacity: 1, x: 180 },
//     expand: {
//       x: 0,
//       width: 50,
//       transition: { duration: 2, ease: "easeOut" },
//     },
//     fadeOut: {
//       opacity: 0,
//       transition: { duration: 1, delay: 3 },
//     },
//   };

//   return (
//     <motion.div
//       key={animationKey}
//       className="bg-black flex justify-center items-center h-screen overflow-hidden"
//     >
//       <motion.div
//         className="h-[3px] mt-10 mr-2 bg-gray-500 absolute"
//         variants={lineVariant1}
//         initial="hidden"
//         animate={["expand", "fadeOut"]}
//       ></motion.div>
//       <motion.div
//         className="h-[3px] mt-10 mr-2 bg-gray-500 absolute"
//         variants={lineVariant2}
//         initial="hidden"
//         animate={["expand", "fadeOut"]}
//       ></motion.div>

//       <motion.svg
//         className="pizza-svg"
//         xmlns="http://www.w3.org/2000/svg"
//         viewBox="0 0 100 100"
//         width={200}
//         height={500}
//         variants={svgVariants}
//         initial="hidden"
//         animate={["visible", "movedRight", "zoomed"]}
//       >
//         <motion.path
//           variants={pathVariants}
//           initial="hidden"
//           animate={["visible", "fullWhite"]}
//           fill="none"
//           stroke="white"
//           strokeWidth={1}
//           d="M40 40 L80 40 C80 40 80 80 40 80 C40 80 0 80 0 40 C0 40 0 0 40 0Z"
//         />
//         <motion.path
//           variants={pathVariants}
//           initial="hidden"
//           animate={["visible", "fullWhite"]}
//           stroke="white"
//           strokeWidth={1}
//           fill="none"
//           d="M50 30 L50 -10 C50 -10 90 -10 90 30 Z"
//         />
//       </motion.svg>

//       {/* Render the actual content after animation */}
//       <motion.div
//         initial={{ opacity: 0 }}
//         animate={{ opacity: 1 }}
//         transition={{ duration: 2, delay: 3 }}
//       >
//         <html lang="en">
//         <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         </body>
//         </html>
//       </motion.div>
//     </motion.div>
//   );
// }
